services:
  backend:
    build: ./backend
    container_name: Misson4-CarInsurance-Backend
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      container_name: Misson4-CarInsurance-Frontend
      environment:
        NODE_ENV: production
      ports:
        - '5173:5173'
 